services:
  deepspeed-training:
    build:
      context: .
      dockerfile: ${DOCKERFILE_PATH:-dockerfiles/Dockerfile-A10-22.04}
    image: deepspeed-training:latest
    container_name: deepspeed-training

    # Running in network-host mode ensures that the node network is visible to
    # processes within the container.
    # If running without host mode, DeepSpeed's master port must be exposed to
    # the container.  I.e.
    # ports:
    #   - "${SSH_PORT:-22}:${SSH_PORT:-22}"
    #   - "${DOCKER_MASTER_PORT:-29500}:${DOCKER_MASTER_PORT:-29500}"
    network_mode: "host"
    
    privileged: true
    runtime: nvidia

    ulimits:
      # Defaults from 
      # https://lambdalabs.atlassian.net/wiki/spaces/HPC/pages/582844431/DeepSpeed+Cluster+ML+Test+Guide#Adjust-file-and-memory-limits-if-necessary-(%3E32-nodes)
      nofile:
        soft: ${DOCKER_NOFILE_SOFT:-2000000}
        hard: ${DOCKER_NOFILE_HARD:-2000000}
      noproc:
        soft: ${DOCKER_NOPROC_SOFT:-1000000}
        hard: ${DOCKER_NOPROC_HARD:-1000000}
      # Unlimited memlock is required both for running large workflows and for integration
      # with infiniband, so we always set to infinity
      memlock:
        soft: -1
        hard: -1
    
    command: /workspace/DeepSpeedExamples/applications/DeepSpeed-Chat/docker_scripts/entrypoint.sh
    
    environment:
      - PROJECT_PATH=${PROJECT_PATH:-/workspace}
      - HF_HOME=${PROJECT_PATH:-/workspace}/.cache/huggingface
      - TRANSFORMERS_CACHE=${PROJECT_PATH:-/workspace}/.cache/huggingface/transformers
      - HF_DATASETS_CACHE=${PROJECT_PATH:-/workspace}/.cache/huggingface/datasets
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # Expose ports to the container environment
      - SSH_PORT=${DOCKER_SSH_PORT:-5100}
      - MASTER_PORT=${DOCKER_MASTER_PORT:-29500}
    
    volumes:
      # Mount DeepSpeedExamples repo to /workspace/DeepSpeedExamples
      - ${HOST_REPO_PATH}:${PROJECT_PATH}/DeepSpeedExamples:rw
      
      # Mount cache to /workspace/.cache
      - ${HOST_CACHE_PATH}:${PROJECT_PATH}/.cache:rw

      # Mount ssh keys to a temporary volume
      # Volume is temporary because we need to change the permissions on .ssh files to root
      # within the container
      - ~/.ssh:/tmp/host_ssh:ro
    
    stdin_open: true
    tty: true
    ipc: host
    shm_size: '1500gb'
    
    working_dir: /workspace/DeepSpeedExamples/applications/DeepSpeed-Chat/training
