services:
  deepspeed-training:
    build:
      context: .
      dockerfile: Dockerfile
    image: deepspeed-training:latest
    container_name: deepspeed-training
    network_mode: "host"
    
    privileged: true
    runtime: nvidia
    
    command: /workspace/DeepSpeedExamples/applications/DeepSpeed-Chat/entrypoint.sh
    
    environment:
      - PROJECT_PATH=${PROJECT_PATH:-/workspace}
      - HF_HOME=${PROJECT_PATH:-/workspace}/.cache/huggingface
      - TRANSFORMERS_CACHE=${PROJECT_PATH:-/workspace}/.cache/huggingface/transformers
      - HF_DATASETS_CACHE=${PROJECT_PATH:-/workspace}/.cache/huggingface/datasets
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      # Expose the ports to the container environment
      # Note that docker doesn't support defining defaults through variables, so any change to port defaults
      # needs to be made both in the port bindings and in the exposed port variables
      - SSH_PORT=${DOCKER_SSH_PORT:-5100}
      - MASTER_PORT=${DOCKER_MASTER_PORT:-29500}
    
    volumes:
      # Mount DeepSpeedExamples repo to /workspace/DeepSpeedExamples
      - ${HOST_REPO_PATH}:${PROJECT_PATH}/DeepSpeedExamples:rw
      
      # Mount cache to /workspace/.cache
      - ${HOST_CACHE_PATH}:${PROJECT_PATH}/.cache:rw

      # Mount ssh keys to a temporary volume
      # Volume is temporary because we need to change the permissions on .ssh files to root
      # within the container
      - ~/.ssh:/tmp/host_ssh:ro
    
    stdin_open: true
    tty: true
    ipc: host
    shm_size: '32gb'
    
    working_dir: /workspace/DeepSpeedExamples/applications/DeepSpeed-Chat/training
